version: '3.8'

services:
  backend:
    container_name: smchit-api-users
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: smchitfund-mysql
      DB_PORT: 3306
    depends_on:
      - mysql
    networks:
      - smchitnet

  frontend:
    container_name: smchitfund-react
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - smchitnet

  mysql:
    container_name: smchitfund-mysql
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mychitfund
      MYSQL_USER: root
    networks:
      - smchitnet

networks:
  smchitnet:
    driver: bridge
